when:
  - event: push
    branch: main
  - event: cron
    cron: Daily

steps:
- name: publish
  image: woodpeckerci/plugin-docker-buildx
  settings:
    repo: safhdev/corosyncdevice
    platforms: linux/amd64,linux/arm64,linux/386,linux/armv7
    tags: debiantrixie
    dockerfile: Dockerfile-Debiantrixie
    provenance: mode=max
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_token