when:
  - event: push
    branch: main
  - event: cron
    cron: weekly
  - event: manual

steps:
  - name: docker-build-and-push-debiantrixie
    image: woodpeckerci/plugin-docker-buildx:5.0.0
    privileged: true
    settings:
      registry: https://index.docker.io/v1/
      repo: safhdev/corosyncdevice
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

      dockerfile: Dockerfile-debiantrixie
      context: .

      platforms:
        - linux/amd64
        - linux/arm64
        - linux/386
        - linux/armv7

      tags:
        - debiantrixie

      pull_image: true
      provenance: mode=max
      sbom: true

      labels:
        - org.opencontainers.image.source=${CI_REPO_URL}