matrix:
  include:
    - DOCKERFILE: Dockerfile-Debiantrixie
      TAG: debiantrixie
    - DOCKERFILE: Dockerfile-Debianbookworm
      TAG: debianbookworm
    - DOCKERFILE: Dockerfile-Debiantest
      TAG: debiantest

when:
  - event: push
    branch: main
  - event: cron
    cron: weekly
  - event: manual

steps:
  - name: docker-build-and-push
    image: woodpeckerci/plugin-docker-buildx:latest
    privileged: true
    settings:
      registry: https://index.docker.io/v1/
      repo: safhdev/corosyncdevice
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ${DOCKERFILE}
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/386
        - linux/arm/v7
      tags:
        - ${TAG}
      pull_image: true
      provenance: mode=max
      sbom: true
      cache_images:
        - safhdev/corosyncdevice:${TAG}-cache
      buildkit_oci_max_parallelism: 2
      buildkit_debug: true
      labels:
        - org.opencontainers.image.source=${CI_REPO_URL}
        - org.opencontainers.image.revision=${CI_COMMIT_SHA}
        - org.opencontainers.image.version=${CI_COMMIT_BRANCH}-${CI_PIPELINE_NUMBER}